sudo: required

services:
  - docker

before-install:
  - docker pull lambci/lambda:build
  - curl -Lo zappa.zip https://github.com/danielwhatmuff/zappa/archive/master.zip  && unzip zappa.zip
  - cd zappa

script:
  - docker build -t mcrowson/zappa-builder .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push mcrowson/zappa-builder
