sudo: required

services:
  - docker

before-install:
  - docker pull lambci/lambda:build

script:
  - curl -Lo zappa.zip https://github.com/mcrowson/zappa-1/archive/master.zip && unzip zappa.zip
  - cd zappa-master
  - docker build -t mcrowson/zappa-builder .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push mcrowson/zappa-builder
